# ~/.config/starship.toml

add_newline = true
command_timeout = 1000
format = """ $shellî€‡$os$hostname$username$directory$git_branch$git_status$nodejs$package"""

# Drop ugly default prompt characters
[character]
success_symbol = ''
error_symbol = ''

# ------------------------------------

[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Windows = ' ï…º'
Arch = ' ó°£‡'
Ubuntu = ' ïŒ›'
Macos = ' ó°€µ'

# Shows the Username
[username]
show_always = true
style_root = "bold red"
style_user = "bold gray"
format = "[$user]($style) "
disabled = false

# Shows the hostname
[hostname]
ssh_only = false
format = '[$hostname](bold yellow)/'
disabled = false

# Shows current directory
[directory]
truncation_length = 1
# truncation_symbol = 'ï» '
truncation_symbol = 'ï’‚ '
home_symbol = 'ó°‹œ ~'
read_only_style = '197'
read_only = ' ï€£ '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
format = '[$symbol$branch]($style)'
symbol = "î™ "
truncation_symbol = 'â€¦/'
style = 'bold red'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = 'ğŸ³'
up_to_date = ''
untracked = ' ï”©'
ahead = ' â‡¡${count}'
diverged = ' â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = ' â‡£${count}'
stashed = ' ï£–'
modified = ' ï„'
staged = '[ ++\($count\)](green)'
renamed = ' è¥'
deleted = ' ï€”'
windows_starship = '/mnt/c/Users/gaura/.config/starship.exe'

# Shows current nodejs
[nodejs]
format = '[$symbol ($version )]($style)'
symbol = "îœ˜"
not_capable_style = "bold red"

# Shows current shell
[shell]
powershell_indicator = 'ï‘ _'
unknown_indicator = 'mystery shell'
bash_indicator = 'î¯Š'
zsh_indicator = 'î¯Š'
cmd_indicator = 'î¯„'
style = 'bold'
disabled = false
