# ~/.config/starship.toml

add_newline = true
command_timeout = 1000
format = """ $shell$os$username$hostname$kubernetes$directory$git_branch$git_status$nodejs$package"""

# Drop ugly default prompt characters
[character]
success_symbol = '[ó°„´](bold green)'
error_symbol = '[î¯¦] (bold red)'

# Shows the currently used shell
[shell]
powershell_indicator = 'ï‘ _'
unknown_indicator = 'îˆ¸'
bash_indicator = 'î¯Š'
zsh_indicator = 'î‰¤'
cmd_indicator = 'î¯„'
style = 'bold'
disabled = false

# Shows the os
[os]
format = '[$symbol](bold white) '
disabled = false

# os symbols
[os.symbols]
Windows = ' ï…º'
Arch = ' ó°£‡'
Ubuntu = ' ïŒ›'
Macos = ' ó°€µ'

# Shows the username
[username]
style_user = 'yellow bold'
style_root = 'black bold'
format = '[î€‡ ](white bold)[$user]($style) '
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)'
disabled = false

# Shows current directory
[directory]
truncation_length = 1
truncation_symbol = 'ï’‚ '
truncate_to_repo = true
home_symbol = 'ó°‹œ ~'
read_only_style = ' 197'
read_only = ' ï€£'
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
format = '[$symbol$branch]($style)'
symbol = "î™ "
truncation_symbol = 'â€¦/'
style = 'bold red'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = 'ğŸ³'
up_to_date = ''
untracked = ' ï”©'
ahead = ' â‡¡${count}'
diverged = ' â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = ' â‡£${count}'
stashed = ' ï£–'
modified = ' ï„'
staged = '[ ++\($count\)](green)'
renamed = ' è¥'
deleted = ' ï€”'
windows_starship = '/mnt/c/Users/gaura/.config/starship.exe'

# Shows current nodejs
[nodejs]
format = '[$symbol ($version )]($style)'
symbol = "îœ˜"
not_capable_style = "bold red"

# Shows kubernetes context and namespace
[kubernetes]
format = '[ó±ƒ¾ $context\($namespace\)](bold purple) '
disabled = false
