# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

promptToReturnFromSubprocess: false
disableStartupPopups: true
notARepository: "skip"
update:
  method: "never"

git:
  commit:
    signOff: true
  overrideGpg: true
  parseEmoji: true

gui:
  authorColors:
    "gaurav2361": "#ffa500"
    "Gaurav": "#ffa500"
  showIcons: true
  showFileIcons: true
  showListFooter: true
  showRandomTip: false
  showCommandLog: true
  showBottomLine: true
  nerdFontsVersion: "3"

os:
  editPreset: "nvim"

theme:
  activeBorderColor:
    - "#cba6f7"
    - bold
  inactiveBorderColor:
    - "#a6adc8"
  optionsTextColor:
    - "#89b4fa"
  selectedLineBgColor:
    - "#313244"
  cherryPickedCommitBgColor:
    - "#45475a"
  cherryPickedCommitFgColor:
    - "#cba6f7"
  unstagedChangesColor:
    - "#f38ba8"
  defaultFgColor:
    - "#cdd6f4"
  searchingActiveBorderColor:
    - "#f9e2af"
